spring:
  application:
    name: ops-statistics-service-spring

  datasource:
    url: jdbc:sqlserver://devcluster\devserv;databaseName=BANK2000;integratedSecurity=true;encrypt=false
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  rabbitmq:
    host: test-rabbit-srv.bsb.ge
    port: 5672
    username: test
    password: Qwer@1234
    virtual-host: B6dev

app:
  rabbitmq:
    queue: basis.statistics.queue.v2
    exchange: B6.Transactions
    create-routing-key: b6.transaction.create
    delete-routing-key: b6.transaction.delete

    dlx: basis.statistics.queue.v2.dlx
    dlq: basis.statistics.queue.v2.dlq
    dead-letter-routing-key: basis.statistics.queue.v2.dead